# Generated by Django 3.1.4 on 2021-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210330_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
