# Generated by Django 3.1.4 on 2021-04-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session_token',
        ),
    ]
