# Generated by Django 3.1.4 on 2021-04-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_user_session_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(upload_to='static/images'),
        ),
    ]
