# Generated by Django 3.1.4 on 2021-04-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210415_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(upload_to='static/images'),
        ),
    ]
